version: '3'
services:
  devDB:
    container_name: truec-dev-db
    image: postgres:11.6-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=truec-dev
    volumes:
      - ./docker-volumes/postgresql-dev:/var/lib/postgresql
